- Download/installer.sh
- src/EPGGrabber/providers/beinConnect.py
- src/EPGGrabber/version
Update bein sport connect Remove XTRA 1/2 (Thank's @MOHAMED19OS)
> Bump V 18.2

- Download/installer.sh
- configs/bein.channels.xml
- configs/custom.sources.xml
- src/EPGGrabber/api/bouquets.json
- src/EPGGrabber/version
Merge and improve Bein sources into one file (Thank's @MOHAMED19OS)
> Bump V 18.3

- src/EPGGrabber/providers/beinConnect.py
add  id for channel bein Sport FR 1,2,3
> add bein fr id

- src/EPGGrabber/api/bouquets.json
Add New channels : bein max for provider Bein.net
> New channels : bein max

- Download/installer.sh
- src/EPGGrabber/version
Add New channels : bein max for provider Bein.net
> Bump V18.6

- src/EPGGrabber/api/bouquets.json
add new changes for Channels Rotana
> Update Channels Rotana

- src/EPGGrabber/providers/beinConnect.py
> Disable Bein max

- src/EPGGrabber/api/bouquets.json
> Update bouquets Rotana

- Download/installer.sh
- src/EPGGrabber/providers/mbc.py
- src/EPGGrabber/version
UnboundLocalError: local variable 'nm' referenced before assignment
> Fix Mbc Epg

- Download/installer.sh
- src/EPGGrabber/providers/beinConnect.py
- src/EPGGrabber/providers/beinentC.py
- src/EPGGrabber/version
-Try to fix (certificate verify failed) on some images...
(requests.exceptions.sslerror: ("bad handshake: error([('ssl routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",) site:stackoverflow.com)
> Bump V 19.7

- Download/installer.sh
- src/EPGGrabber/providers/rotana.py
- src/EPGGrabber/version
Remove print codes forget it from testing
> ump V 19.9

- Download/installer.sh
- src/EPGGrabber/providers/rotana.py
- src/EPGGrabber/version
> Bump V 20.0

- configs/discovery.channels.xml
Update Reference and delete channel for Astra 4.8E And add channel for Eutelsat 9B
> Update  discovery.channels

- configs/custom.channels.xml
Delete old Reference And Update with the new Reference For AD SPORTS 3 HD & AD SPORTS 4 HD In 7W
> Update Reference For AD SPORTS 3 HD & AD SPORTS 4 HD

- configs/bein.channels.xml
Add Id For bein Xtra 1 & 2 In  Nile sat 7W and badr 26E
> Add Id For bein Xtra 1 & 2

- src/EPGGrabber/providers/beinConnect.py
Add bein Max 1 & 2 And Add bein Xtra 1 & 2  in beinConnect
> Add bein Max  And bein Xtra

- Download/installer.sh
- src/EPGGrabber/version
-Update bein channel Id
-Fix url beIN net ar
-Disable bein max For now
-fix url bein entertainment
> Bump V20.5

- src/EPGGrabber/providers/elcin.py
delete some channel and add new
> Update elcinema Arab

- Download/installer.sh
- src/EPGGrabber/version
-Update elcinema.channels (by MOHAMED19OS)
-Update elcinema Arab (by MOHAMED19OS)
> Bump V20.6

- Download/installer.sh
- src/EPGGrabber/version
-Update bouquets For Last Change (by MOHAMED19OS)
-Update Id For last Change ROtana (by MOHAMED19OS)
> Bump V20.7

- Download/installer.sh
- src/EPGGrabber/version
-Add beIN SPORTS, AFC and Al Kass by (MOHAMED19OS)
> Bump V21.4

- Download/installer.sh
- src/EPGGrabber/version
> Bump V21.5

- Download/installer.sh
- src/EPGGrabber/version
Update Channel list for Discovery
> Bump V21.6

- Download/installer.sh
- src/EPGGrabber/version
*some Fix and Update For Script and id channels
* Update Channel name and Id for osn and discovery
* try fix time for SatTV
* Update bein Connect add read and update list channel
* Update bein.net entertainment
* fix name xml in bein.net entertainment
* Update channel id for bein sport and entertainment
* fix discovery script
* fix name channel in beinent script
* Update bouquets.json
Co-authored-by: MOHAMED19OS <mohamed_os@gmail.com>
> Bump V21.7

- Download/installer.sh
- src/EPGGrabber/version
-Fix Url beinConnect
Co-authored-by: MOHAMED19OS <mohamed_os@gmail.com>
> Bump V21.8

- Download/installer.sh
- src/EPGGrabber/version
Update ID Osn Channel by @MOHAMED19OS
> Bump V22.1

- Download/installer.sh
- src/EPGGrabber/version
-Fix  beinentC crash error
-Fix rotana cloudflare protection.
> Bump V22.2

- Download/installer.sh
- src/EPGGrabber/version
> Bump V22.3

- Download/installer.sh
- src/EPGGrabber/providers/beincin.py
- src/EPGGrabber/providers/elcin.py
- src/EPGGrabber/version
> Bump V22.4

- src/EPGGrabber/version
Add new source by @ostende 
* added bebawy6 source
* added bebawy source
> Bump V22.6

- Download/installer.sh
- src/EPGGrabber/version
https://github.com/zKhadiri/Epg-plugin/commit/e2300c48445be5a4d349fb67e90fc3a76abe379b
https://github.com/zKhadiri/Epg-plugin/commit/84268beeb0a576ebea093863514c466f28d0174f
> Bump V22.7

- README.md
- src/EPGGrabber/providers/elcin.py
> fix elcin.py error 

- Download/installer.sh
- src/EPGGrabber/version
> Bump V22.8

- configs/custom.sources.xml
- src/EPGGrabber/api/bouquets.json
- src/EPGGrabber/api/providers.json
- src/EPGGrabber/core/check.py
> uploaded by iet5

- Download/installer.sh
- src/EPGGrabber/version
- Some fix for El Cinma by iet5
> Bump V22.9

- Download/installer.sh
- src/EPGGrabber/version
> Bump V23.2

- Download/installer.sh
- src/EPGGrabber/version
-Some fixes and update Bein Sports by Saiedf
> Bump V23.4

- Download/installer.sh
- src/EPGGrabber/version
- Update Channel Assign by Saiedf
> Bump V23.5

- Download/installer.sh
- src/EPGGrabber/version
> Bump V23.8

- Download/installer.sh
- src/EPGGrabber/version
> Bump V23.9

- configs/custom.sources.xml
- src/EPGGrabber/core/check.py
Fix some minor errors by Saiedf
> Fix some minor errors by Saiedf

- Download/installer.sh
- src/EPGGrabber/version
* Fix some minor errors by Saiedf
> Bump V24.0

- Download/installer.sh
- src/EPGGrabber/version
* Fixes to make Script Provider work with Dreambox by Saiedf
> Bump V24.1

- src/EPGGrabber/providers/freesat.py
- src/EPGGrabber/providers/lovenature.py
Update lovenature – freesat  Script by ** angel_heart **
> Update lovenature – freesat  Script by ** angel_heart **

- Download/installer.sh
- src/EPGGrabber/version
* Update lovenature – freesat Script by ** angel_heart **
> Bump V24.2

- Download/installer.sh
- src/EPGGrabber/version
> Bump V24.3

- configs/custom.sources.xml
- configs/qatar6iet5.channels.xml
- configs/rotana.channels.xml
- configs/saudiarabia2iet5.channels.xml
- configs/uae2iet5.channels.xml
- src/EPGGrabber/api/bouquets.json
- src/EPGGrabber/api/providers.json
- src/EPGGrabber/core/check.py
- src/EPGGrabber/providers/egypt2iet5.py
- src/EPGGrabber/providers/elcin.py
- src/EPGGrabber/providers/elcinEN.py
- src/EPGGrabber/providers/poland1iet5.py
- src/EPGGrabber/providers/poland2iet5.py
- src/EPGGrabber/providers/qatar1iet5.py
- src/EPGGrabber/providers/qatar2iet5.py
- src/EPGGrabber/providers/qatar3iet5.py
- src/EPGGrabber/providers/qatar4iet5.py
- src/EPGGrabber/providers/qatar5iet5.py
- src/EPGGrabber/providers/qatar6iet5.py
- src/EPGGrabber/providers/saudiarabia1iet5.py
- src/EPGGrabber/providers/saudiarabia2iet5.py
- src/EPGGrabber/providers/saudiarabia3iet5.py
- src/EPGGrabber/providers/saudiarabia4iet5.py
- src/EPGGrabber/providers/uae1iet5.py
- src/EPGGrabber/providers/uae2iet5.py
- src/EPGGrabber/providers/uae3iet5.py
- src/EPGGrabber/providers/uae5iet5.py
Make the plugin import the time zone from the receiver's time  - By iet5
> Import Time Zone from Receiver Time  - By iet5

- Download/installer.sh
- src/EPGGrabber/version
* Import Time Zone from Receiver Time - By iet5
> Bump V24.5

- Download/installer.sh
- src/EPGGrabber/version
> Bump V24.6
